version: '3.8'

services:

  lweb:
    container_name: lweb
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn lending.wsgi:application --bind :8078
    volumes:
      - static_volume:/home/app/lweb/staticfiles
      - media_volume:/home/app/lweb/mediafiles
    expose:
      - 8078
    env_file:
      - ./.env.prod

  lnginx:
    container_name: lnginx
    build: ./nginx
    volumes:
      - static_volume:/home/app/lweb/staticfiles
      - media_volume:/home/app/lweb/mediafiles
    ports:
      - 8079:8079
    depends_on:
      - lweb
  
  ldb:
    container_name: ldb
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    command: -p 5435
    env_file:
      - ./.env.prod.db
  

networks:
  default:
    name: nginxproxymanager_default
    external: true

volumes:
  static_volume:
  media_volume:
  postgres_data:
