# Generated by Django 3.2.16 on 2023-01-16 06:28

import ckeditor.fields
import client.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Название колмплекса')),
                ('square', models.CharField(help_text='Например: от 200 до 1500', max_length=20, verbose_name='Доступная площядь')),
                ('price', models.FloatField(verbose_name='Цена за м2')),
                ('title_image', models.ImageField(help_text='Певрая фотография на странице', upload_to=client.models.save_path, verbose_name='Обложка')),
                ('presentation', models.FileField(upload_to=client.models.save_path, verbose_name='Презентация проекта')),
                ('second_image', models.ImageField(upload_to=client.models.save_path, verbose_name='Фото к описанию')),
                ('desciption', ckeditor.fields.RichTextField(max_length=900, verbose_name='Описание')),
                ('map', models.TextField(max_length=1000, verbose_name='Скрипт карты')),
                ('is_published', models.BooleanField(blank=True, default=True, verbose_name='Опубликован')),
                ('wh_link', models.CharField(max_length=580, verbose_name='Ссылка WhatsApp')),
                ('tg_link', models.CharField(max_length=580, verbose_name='Ссылка Telegramm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.site', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Комплекс',
                'verbose_name_plural': 'Комплексы',
            },
        ),
        migrations.CreateModel(
            name='SiteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(help_text='Название сайта во вкладке', max_length=80, verbose_name='Заголовок сайта')),
                ('meta_description', models.TextField(help_text='Описание сайта (для ссылки) CEO', max_length=500, verbose_name='Краткое описание (СЕО)')),
                ('scripts', models.TextField(max_length=1500, verbose_name='Скрипты аналитики')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Данные сайта',
                'verbose_name_plural': 'Данные сайтов',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=client.models.save_path, verbose_name='Фотография')),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.complex', verbose_name='Комплекс')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Апартаментов или Вилл', max_length=180, verbose_name='Название')),
                ('amount', models.IntegerField(verbose_name='Колличество')),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.complex', verbose_name='Комплекс')),
            ],
            options={
                'verbose_name': 'Особенность',
                'verbose_name_plural': 'Особенности',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=32, null=True, verbose_name='Почта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.site', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Security', 'Безопасность'), ('Layout', 'Планировка'), ('Interior', 'Внутренняя отделка'), ('Concept', 'Концепция дома'), ('Infrastructure', 'Инфраструктура'), ('Location', 'Расположение'), ('Architecture', 'Архитектура'), ('Concierge', 'Консьерж сервис'), ('Parks', 'Парки'), ('Schools', 'Школы'), ('Entertainment', 'Театры и кино'), ('Hospitals', 'Больницы и мед центры')], max_length=180, verbose_name='Название')),
                ('desciption', ckeditor.fields.RichTextField(max_length=900, verbose_name='Описание')),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.complex', verbose_name='Комплекс')),
            ],
            options={
                'verbose_name': 'Приемущество',
                'verbose_name_plural': 'Приемущества',
            },
        ),
    ]
