# Generated by Django 3.2.16 on 2023-01-16 07:24

import client.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_advantage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='complex',
            name='private',
            field=models.BooleanField(blank=True, default=False, verbose_name='Отобразить как отдельный сайт'),
        ),
        migrations.AddField(
            model_name='complex',
            name='slug',
            field=models.SlugField(default=None, max_length=180, verbose_name='Название страницы (латиницей)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advantage',
            name='image',
            field=models.ImageField(help_text='Фотография на задний фон', upload_to=client.models.save_path, verbose_name='Фотография'),
        ),
    ]
