# Generated by Django 3.2.16 on 2023-01-16 07:46

import client.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20230116_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='complex',
            name='logo',
            field=models.FileField(null=True, upload_to=client.models.save_path, verbose_name='Логотип'),
        ),
    ]
