# Generated by Django 3.2.16 on 2023-01-16 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_complex_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.sitedata', verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.sitedata', verbose_name='Сайт'),
        ),
    ]
