# Generated by Django 3.2.16 on 2023-01-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20230116_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complex',
            name='price',
            field=models.IntegerField(verbose_name='Цена за м2'),
        ),
    ]
