# Generated by Django 3.2.16 on 2023-01-16 09:02

import client.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_alter_advantage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='complex',
            name='bg_image',
            field=models.ImageField(null=True, upload_to=client.models.save_path, verbose_name='Фото на задний пдан формы'),
        ),
    ]
