# Generated by Django 3.2.16 on 2023-01-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='desciption',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='Описание'),
        ),
    ]
