# Generated by Django 3.2.16 on 2023-01-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_complex_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='complex',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='Контактный телефон'),
        ),
    ]
