# Generated by Django 3.2.17 on 2023-02-06 07:09

import ckeditor.fields
import client.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('client', '0015_complex_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='complex',
            options={'verbose_name': 'Complex', 'verbose_name_plural': 'Complexes'},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'Peculiarity', 'verbose_name_plural': 'Peculiarities'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Photo', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterModelOptions(
            name='layout',
            options={'verbose_name': 'Планировка', 'verbose_name_plural': 'Layouts'},
        ),
        migrations.AlterModelOptions(
            name='sitedata',
            options={'verbose_name': 'Site Data', 'verbose_name_plural': 'Site Data'},
        ),
        migrations.AlterField(
            model_name='advantage',
            name='complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.complex', verbose_name='Complex'),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='desciption',
            field=ckeditor.fields.RichTextField(max_length=900, verbose_name='Desciption'),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='name',
            field=models.CharField(choices=[('Security', 'Security'), ('Layout', 'Планировка'), ('Interior', 'Interior'), ('Decoration', 'Decoration'), ('Infrastructure', 'Infrastructure'), ('Location', 'Location'), ('Architecture', 'Architecture'), ('Concierge', 'Concierge'), ('Parks', 'Parks'), ('Schools', 'Schools'), ('Entertainment', 'Entertainment'), ('Hospitals', 'Hospitals')], max_length=180, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.sitedata', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='bg_image',
            field=models.ImageField(null=True, upload_to=client.models.save_path, verbose_name='Photo on the background of the form'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='ctype',
            field=models.CharField(blank=True, default='', help_text='Ex: Клубный Дом, Жилой Комплекс и тд', max_length=180, verbose_name='Complex Type'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='desciption',
            field=ckeditor.fields.RichTextField(max_length=900, verbose_name='Desciption'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='is_published',
            field=models.BooleanField(blank=True, default=True, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='logo',
            field=models.FileField(null=True, upload_to=client.models.save_path, verbose_name='Logotype'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='map',
            field=models.TextField(max_length=1000, verbose_name='Map script'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='name',
            field=models.CharField(max_length=180, verbose_name='Complex Nmae'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='price',
            field=models.IntegerField(verbose_name='Price per m2'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='private',
            field=models.BooleanField(blank=True, default=False, verbose_name='Display as standalone site'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='second_image',
            field=models.ImageField(upload_to=client.models.save_path, verbose_name='Photo description'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='short',
            field=models.CharField(help_text='Short phrase', max_length=180, verbose_name='Short desciption'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.sitedata', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='slug',
            field=models.SlugField(max_length=180, verbose_name='Complex name (EN)'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='square',
            field=models.CharField(help_text='For example: from 200 to 1500', max_length=20, verbose_name='Available Square'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='tg_link',
            field=models.CharField(max_length=580, verbose_name='Telegramm link'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='title_image',
            field=models.ImageField(help_text='First photo on the page', upload_to=client.models.save_path, verbose_name='Tittle image'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Changed'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='video_link',
            field=models.CharField(blank=True, default=None, max_length=580, null=True, verbose_name='Link to Video'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='wh_link',
            field=models.CharField(max_length=580, verbose_name='WhatsApp link'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.complex', verbose_name='Complex'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(help_text='Например: Апартаментов или Вилл', max_length=180, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='image',
            name='complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.complex', verbose_name='Complex'),
        ),
        migrations.AlterField(
            model_name='layout',
            name='complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.complex', verbose_name='Complex'),
        ),
        migrations.AlterField(
            model_name='layout',
            name='desciption',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='Desciption'),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='meta_description',
            field=models.TextField(help_text='Site desciption (SEO)', max_length=500, verbose_name='Short desciption'),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='meta_title',
            field=models.CharField(help_text='Site Name', max_length=80, verbose_name='Tittle'),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='scripts',
            field=models.TextField(max_length=1500, verbose_name='Analitics Scripts'),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='Site'),
        ),
    ]
