# Generated by Django 3.2.18 on 2023-03-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_complex_title_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complex',
            name='title_phone',
            field=models.CharField(max_length=20, null=True, verbose_name='Контактный телефон (заголовок)'),
        ),
    ]
